### ISSUE TITLE
Home page redesign milestones

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#105]
- [x] Add button and change home page's head-line text.
- [x] New "Problem that students face" section.
- [x] Transfer "As seen in" section from About to Home page.
- [x] New "Oppia's info" section:  what is the link for "The Oppia Difference"?Partnerships? Are we keeping the laptop?
- [x] New "Impact and Testimonials" section: more testimonial or just two?
- [x] New "Be part of the change" section: other tab's text is needed
- [x] Email form at the bottom ( Contact us form is a link?)
