### ISSUE TITLE
Partnerships page redesign milestones

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#115]
- [x] Obtain and minimize new photo.
- [x] Redesign hero card.
- [x] Implement instruction card for new partnership.
- [x] Remove old codes and unused CSS classes.
