### ISSUE TITLE
Partnerships page Milestone Tracker

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#14]
- [ ] Setup basic page layout. 
-  [ ] Replace placeholder, obtain icon assets from designer for improved responsiveness
-  [ ] Back-end for email form. Need to figure out which tools/tech to use.
-  [ ] UX / Responsiveness touch up
-  [ ] Additional milestones as needed.

07/25 update: At the point of writing this, I have received the early July mocks, both mobile and web version. Attempts have been made to match responsiveness  / layout on both fronts( mobile and regular browser view)
