### ISSUE TITLE
Donate page Milestone Tracker

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#16]
- [x] Setup basic page layout
- [ ] Obtain high res donate_works image ( the same image for oppia.org/donate )
- [ ] Fill out links and buttons (CC and Paypal button, amazon smile link).
- [ ] Make the image more interactive? Need discussion on this.
- [ ] UI/UX touchup as needed.
- [ ] More milestone as needed.
