### ISSUE TITLE
Email functionality milestones

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#30]
- [x] Setup backend logic to handle sending info from front-end to admin as email.
- [x] Trigger a UI event when user hit "Submit" on the form.
- [x] Logging front-end error or back-end error.

@seanlip any advise on logging errors?

**Comment by seanlip** [comment]
For frontend errors I think we should call a handler that reports it to the backend so it shows up in the logs. 

For backend errors, I guess it depends. E.g. we need a 404 page right?

And then, for all errors (except 404s for pages we don't recognize), we should probably email a mailing list forwarded to site devs (probably you + me for now).

Sg?

**Comment by seanlip** [comment]
Actually, just routing folks to the homepage seems even better to me.

**Comment by hoangviet1993** [comment]
All check-point accomplished!
