### ISSUE TITLE
Navigation bar design milestones

### ISSUE THREAD

**Issue by hoangviet1993** [oppia/foundation-website#6]
- [x] Initial commit to setup navbarDirective and replace old design with material design
- [x] Obtain foundation logo from designers, make "Donate" more button-like and add bottom-shadow to match mocks
- [x] Obtain decision on type of navbar for small viewport ( left sidebar vs collapsed right sidebar ) and complete implementation.
- [x] (Aug 2018) Jordan feedback: Text's font size is too large.
